spring.application.name=lojasd

# autenticacao Spring
spring.security.user.name=${SPRING_USERNAME}
spring.security.user.password=${SPRING_PASSWORD}

#Importar configurações locais (ficheiro gitignored com credenciais)
spring.config.import=optional:application-local.properties

#MariaDB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Sessões HTTP
server.servlet.session.timeout=30m